import type { Question, Section } from "./types";

// FROZEN QUESTIONNAIRE. Lexi World Discovery (Phase 2, approved).
// Written in plain, easy English. Do not add or remove questions
// without an explicit change request.

export const QUESTIONNAIRE_VERSION = "2.0.0";

export const SECTIONS: Section[] = [
  { id: "vision", title: "Your Vision & Business", blurb: "The big idea, goals, money and dates behind Lexi World." },
  { id: "identity", title: "The Game & Its Story", blurb: "What kind of game this is, and the world it lives in." },
  { id: "experience", title: "How It Feels to Play", blurb: "How a child moves through and feels the game." },
  { id: "characters", title: "Characters & Growing", blurb: "The child's character, guides, levels and rewards." },
  { id: "systems", title: "Items, Quests & Coins", blurb: "The everyday parts that power the game." },
  { id: "learning", title: "Reading & Smart Help", blurb: "How children actually learn to read, and how the game adjusts." },
  { id: "social", title: "Playing With Others", blurb: "Whether children connect, team up or compete." },
  { id: "platform", title: "Devices & Setup", blurb: "Which devices, the look, sound and sign-in." },
  { id: "compliance", title: "Safety & Your Tools", blurb: "Keeping data safe, your admin tools, and what-if cases." },
];

export const QUESTIONS: Question[] = [
  // Your Vision & Business
  {
    id: "biz_vision", number: 1, section: "vision", category: "Your Vision",
    requirementType: "Business", priority: "Critical", kind: "Confirmation + Clarification",
    currentUnderstanding: "Lexi World is a story game that teaches children to read, with special care for children who have dyslexia. The goal is for every child to become a happy, confident reader.",
    confirmationStatement: "The main goal is to help children (especially the roughly 1 in 5 who have dyslexia) become lifelong readers through a game they love.",
    missingInformation: "The real-world result you most want to see (how many children reached, reading results, money earned, or investment).",
    whyWeNeedThis: "It guides every choice we make. We build one way to prove reading results, and another way to get the most downloads.",
    impact: "Without it, we might focus on the wrong things.",
    question: "Picture Lexi World two years from now and it has gone really well. What does that success look like to you? More children reading, better reading results, money earned, or something else?",
    helpText: "Think about the result you would be most proud of.",
    developerNote: "Product, Business, Delivery.",
    input: "paragraph", required: true,
  },
  {
    id: "biz_goals", number: 2, section: "vision", category: "Top Goals",
    requirementType: "Business", priority: "High", kind: "New requirement",
    currentUnderstanding: "The plan is to mix a solid reading program with a fun game world.",
    missingInformation: "Your top three goals for the first version, in order.",
    whyWeNeedThis: "If time or money runs short, we protect your top goals first instead of guessing.",
    impact: "If goals are unclear, the first version gets too big and slips late.",
    question: "If the first version has to nail just three things and everything else can wait, what are those three things, in order?",
    example: "For example: 1) Prove the reading method works, 2) A great first 10 minutes, 3) A simple progress view for parents.",
    developerNote: "Product, Delivery.",
    input: "paragraph", required: true,
  },
  {
    id: "biz_monetization", number: 3, section: "vision", category: "How People Pay",
    requirementType: "Business", priority: "Critical", kind: "New requirement",
    currentUnderstanding: "The documents do not say how people will pay. The meeting mentioned families, schools and reading specialists.",
    missingInformation: "The full plan: family plans, school plans, a free trial, and any in-game purchases, plus rough prices.",
    whyWeNeedThis: "How people pay shapes the sign-up, billing and the whole business side.",
    impact: "Without it, we cannot build payments or check if the numbers add up.",
    question: "How should families and schools get Lexi World? Tick all that fit, and add any thoughts on price below.",
    developerNote: "Business, Backend (billing), Frontend.",
    reference: "Duolingo (free with a paid upgrade), and school-license plans.",
    input: "multi_select",
    options: [
      { value: "trial_sub", label: "Free to try, then a paid plan" },
      { value: "paid_sub", label: "A paid plan (monthly or yearly)" },
      { value: "school", label: "Schools or districts buy it for their students" },
      { value: "iap", label: "Optional extra purchases inside the game" },
      { value: "undecided", label: "Still deciding" },
    ],
    required: true,
  },
  {
    id: "biz_constraints", number: 4, section: "vision", category: "Budget & Deadlines",
    requirementType: "Business", priority: "High", kind: "New requirement",
    currentUnderstanding: "The documents lay out a 24-month plan in five stages, but no budget or hard dates.",
    missingInformation: "A budget range, how long the money lasts, any fixed date, and any team limits.",
    whyWeNeedThis: "These limits help us plan a realistic scope and team size.",
    impact: "Without them, the plan may cost too much or miss key dates.",
    question: "Are there any fixed limits we should plan around? For example a target budget, a launch date tied to a school year or an investor demo, or limits on team size.",
    developerNote: "Delivery, Business.",
    input: "paragraph",
  },
  {
    id: "biz_timeline", number: 5, section: "vision", category: "Timeline",
    requirementType: "Business", priority: "Medium", kind: "Confirmation",
    currentUnderstanding: "A 24-month plan in five stages: Foundation (1 to 3), Vertical Slice (4 to 8), Alpha (9 to 15), Beta (16 to 20), Launch (21 to 24).",
    confirmationStatement: "The plan is a 24-month build in five stages, as written in your documents.",
    whyWeNeedThis: "Confirming the timeline lets us line up the team and milestones.",
    impact: "If the timeline has changed, we need to re-plan the team and scope.",
    question: "Is the 24-month, five-stage plan still your target, or has anything changed, like needing a demo sooner?",
    developerNote: "Delivery.",
    input: "single_select",
    options: [
      { value: "yes", label: "Yes, still the target" },
      { value: "flexible", label: "Flexible" },
      { value: "faster", label: "We need it sooner" },
      { value: "unsure", label: "Not sure" },
    ],
  },
  {
    id: "biz_roadmap", number: 6, section: "vision", category: "Future Plans",
    requirementType: "Business", priority: "Low", kind: "Confirmation + Clarification",
    currentUnderstanding: "Math help (dyscalculia) is noted for later, and the world could grow into books, media and more regions.",
    confirmationStatement: "Math help and a bigger Lexi World are for the future, not the first version.",
    missingInformation: "Which future ideas matter most, so we can leave room for them now.",
    whyWeNeedThis: "Knowing your future plans lets us build in a way that is easy to grow later.",
    impact: "If we ignore this, the setup could be hard to grow.",
    question: "Beyond reading, what is your dream for Lexi World's future? Math, more regions, books or shows? Knowing this helps us leave the right doors open.",
    developerNote: "Product, Architecture.",
    input: "paragraph",
  },

  // The Game & Its Story
  {
    id: "identity_type", number: 7, section: "identity", category: "What Kind of Game",
    requirementType: "Gameplay", priority: "Critical", kind: "Clarification",
    currentUnderstanding: "A fun adventure where children explore kingdoms, do quests, get better at reading and restore the world. The feeling should be warm, adventurous and full of discovery.",
    missingInformation: "Whether it leans more toward learning, an even mix, or more toward a game. And how calm or lively it should feel.",
    whyWeNeedThis: "This one choice shapes the art, the pace and how much it feels like a game versus a lesson.",
    impact: "If this is unclear, we may have to redo art and design later.",
    question: "Imagine two versions side by side. One feels like a cozy learning journey. The other feels like a real adventure game that slips in reading. Which one is closer to your dream?",
    developerNote: "Game Design, Art, Product.",
    reference: "Duolingo (learning first) versus Zelda or Genshin Impact (game first).",
    input: "single_select",
    options: [
      { value: "learning_first", label: "Learning first, with a light game around it" },
      { value: "blend", label: "An even mix of real game and real learning" },
      { value: "game_first", label: "A real game first, that also teaches reading" },
      { value: "unsure", label: "Not sure, help us decide" },
    ],
    required: true,
  },
  {
    id: "identity_loop", number: 8, section: "identity", category: "A Normal Play Session",
    requirementType: "Gameplay", priority: "Critical", kind: "Clarification",
    currentUnderstanding: "Children play through regions, do reading quests, earn rewards, and open the next area once they master a skill.",
    missingInformation: "The step-by-step of what a child does over and over in one sitting.",
    whyWeNeedThis: "This loop is the backbone that every other part connects to.",
    impact: "Without it, the parts get built on their own and do not fit together.",
    question: "Walk us through one 10 to 15 minute play session, like you are describing it over a child's shoulder, from opening the app to the moment they stop.",
    developerNote: "Game Design, Frontend, Backend.",
    reference: "Duolingo's lesson, streak and reward loop. Hay Day's gentle task loop.",
    input: "paragraph", required: true,
  },
  {
    id: "identity_story", number: 9, section: "identity", category: "The Story",
    requirementType: "Gameplay", priority: "High", kind: "Confirmation + Clarification",
    currentUnderstanding: "The full story exists (the Story Tree, the Heart Crystal breaking into 20 Heart Shards, Malvex, The Forgetting, and the Guardians) spread across 20 regions.",
    confirmationStatement: "The founding story and the 20-region setup are the official story we build to.",
    missingInformation: "How the story is told (full voice and animated scenes, or gentle narrated pictures), and whether the story changes for a child who starts at a higher level.",
    whyWeNeedThis: "How it is told changes the voice and animation cost. A story that changes by level means more work.",
    impact: "If undecided, we cannot plan the art and audio, and we risk big rework.",
    question: "How should children experience the story: full voice with animated scenes, or gentle narrated pictures? And should a child who starts at a higher level see a shorter or more advanced version of the story?",
    developerNote: "Story, Art, Audio, Game Design.",
    reference: "Genshin Impact (rich scenes) versus a simple storybook style like Duolingo Stories.",
    input: "paragraph",
  },
  {
    id: "identity_world", number: 10, section: "identity", category: "The World & Regions",
    requirementType: "Gameplay", priority: "High", kind: "Confirmation + Clarification",
    currentUnderstanding: "There are 20 regions, each tied to a reading skill. The first four are named. Places include cities, villages, forests, mountains, rivers and hidden spots.",
    confirmationStatement: "The world is 20 skill-themed regions with lots of different places.",
    missingInformation: "The themes and skills for the other 16 regions, and how many regions go live at launch.",
    whyWeNeedThis: "Region details set the content plan and how big the first version is.",
    impact: "Unknown region details make it hard to plan time and schedule.",
    question: "Could you list the other regions and the reading skill each one teaches? And how many regions would you want ready for the first release?",
    developerNote: "Content, Game Design, Reading, Art.",
    input: "paragraph",
  },

  // How It Feels to Play
  {
    id: "ux_journey", number: 11, section: "experience", category: "The First Time They Open It",
    requirementType: "UX", priority: "High", kind: "Clarification",
    currentUnderstanding: "A child signs in, takes a short starting check, is placed at the right level, plays quests, must master a skill to move on, earns rewards, and moves through regions.",
    missingInformation: "How the first setup works: who sets it up, and what the first five minutes feel like.",
    whyWeNeedThis: "The first few minutes decide if children stay, and shape the sign-in and first screens.",
    impact: "A weak first run loses children and parents right away.",
    question: "The very first time the app is opened, who sets it up, and what should the first five minutes feel like for a brand-new child?",
    developerNote: "UX, Frontend, Backend (accounts).",
    reference: "Duolingo's easy, no-fuss first lesson.",
    input: "paragraph",
  },
  {
    id: "ux_screens", number: 12, section: "experience", category: "The Main Screens",
    requirementType: "UI", priority: "High", kind: "New requirement",
    currentUnderstanding: "The documents describe the world and the reports, but not the app's screens or how a child moves between them.",
    missingInformation: "The main screens (home, map, activity, rewards, profile) and how a child gets around.",
    whyWeNeedThis: "The screen flow is the map for all the on-screen design work.",
    impact: "Without a screen map, the design gets built piece by piece and looks messy.",
    question: "When a child comes back each day, what is the home screen they land on, and what are the main places they can tap to go to from there?",
    developerNote: "UX, UI, Frontend.",
    reference: "Clash Royale's clean home screen. Duolingo's path screen.",
    input: "paragraph",
  },
  {
    id: "ux_accessibility", number: 13, section: "experience", category: "Help for Every Child",
    requirementType: "UX", priority: "High", kind: "Confirmation + Clarification",
    currentUnderstanding: "Because Lexi World is made for children with dyslexia, easy-to-use design is at the heart of it.",
    confirmationStatement: "Easy-to-use, supportive design is core, because the game is for children who find reading hard.",
    missingInformation: "Which supports matter most to you.",
    whyWeNeedThis: "These choices affect the design, the content and the testing throughout.",
    impact: "Missing these would let down the very children the game is for.",
    question: "Which supports are must-haves for your children? Tick all that apply, and add any others below.",
    developerNote: "UX, Frontend, Content, Testing.",
    reference: "Easy-to-read fonts and read-aloud tools.",
    input: "multi_select",
    options: [
      { value: "fonts", label: "Easy-to-read fonts and roomy spacing" },
      { value: "read_aloud", label: "Everything can be read aloud" },
      { value: "calm", label: "Calm colours and less busy screens" },
      { value: "no_timer", label: "No timers or time pressure" },
      { value: "low_distraction", label: "Simple screens with few distractions" },
    ],
  },
  {
    id: "ux_errors", number: 14, section: "experience", category: "When a Child Gets It Wrong",
    requirementType: "UX", priority: "Medium", kind: "Clarification",
    currentUnderstanding: "The game is built around mastering skills, but how it reacts to a wrong answer is not set.",
    missingInformation: "What happens when a child answers wrong (a kind try-again, a hint, encouragement, or a small penalty).",
    whyWeNeedThis: "How we handle mistakes sets the tone and how well children keep learning.",
    impact: "The wrong tone can put off children who already find reading hard.",
    question: "When a child gets something wrong, what should happen?",
    developerNote: "Game Design, UX, Reading.",
    reference: "Duolingo's kind, gentle correction.",
    input: "single_select",
    options: [
      { value: "gentle", label: "Kind. Try again with a hint, no penalty" },
      { value: "small", label: "A small challenge. Maybe lose a star, but easy to win back" },
      { value: "decide", label: "Let your team choose what is best for learning" },
    ],
  },

  // Characters & Growing
  {
    id: "char_design", number: 15, section: "characters", category: "The Child's Character",
    requirementType: "Gameplay", priority: "Medium", kind: "Confirmation + Clarification",
    currentUnderstanding: "The child plays as a Guardian. The plan is a mix-and-match character kit for the child's avatar, the guides and other characters.",
    confirmationStatement: "Children will have a character they can customise, built from a mix-and-match kit.",
    missingInformation: "How much a child can change (look, outfits, unlocks), and whether they earn these or get them free.",
    whyWeNeedThis: "How deep this goes affects the art, the items and the reward loop.",
    impact: "Too little or too much here changes the budget and how much children enjoy it.",
    question: "How important is it that children make their character their own?",
    developerNote: "Art, Game Design, Frontend.",
    reference: "Roblox or Fortnite style avatars, made simpler for children.",
    input: "single_select",
    options: [
      { value: "lots", label: "A lot. A big part of the fun" },
      { value: "little", label: "A little" },
      { value: "set_hero", label: "They play as one set hero" },
      { value: "unsure", label: "Not sure" },
    ],
  },
  {
    id: "char_npc", number: 16, section: "characters", category: "The Guide Characters",
    requirementType: "Gameplay", priority: "Medium", kind: "Confirmation + Clarification",
    currentUnderstanding: "The Lexi Guides and other characters with their own personalities are part of the plan. Guides help children through the world.",
    confirmationStatement: "Friendly guide characters (Lexi Guides) and other characters with personality are part of the game.",
    missingInformation: "What the guides do. Do they give hints, teach, react to progress, or just tell the story?",
    whyWeNeedThis: "What guides do affects the talking system, the hints, and how much voice we record.",
    impact: "If this is vague, the help feels shallow or uneven.",
    question: "Think of the guide as a friendly teacher-buddy. What should they do when a child does well, struggles, or gets stuck?",
    developerNote: "Game Design, Story, Logic, Audio.",
    reference: "Duolingo's characters. The warm feel of Animal Crossing characters.",
    input: "paragraph",
  },
  {
    id: "char_progression", number: 17, section: "characters", category: "Moving Forward & Leveling Up",
    requirementType: "Gameplay", priority: "High", kind: "Confirmation + Clarification",
    currentUnderstanding: "Children move ahead region by region as they master reading skills. They must master a skill before the next region opens.",
    confirmationStatement: "Children move ahead by mastering skills, and must reach mastery to open the next region.",
    missingInformation: "Whether children can go back to earlier areas, and how the game handles a child who races ahead or one who needs more time.",
    whyWeNeedThis: "This sets how areas open, whether they can go back, and how we keep the pace kind.",
    impact: "Poor pacing frustrates fast learners and discourages slower ones.",
    question: "When one child races ahead and another needs more time on the same skill, how should the game treat each of them? And can either one go back to earlier regions?",
    developerNote: "Game Design, Backend, Reading.",
    reference: "Duolingo's way of opening units and letting you practise.",
    input: "paragraph",
  },
  {
    id: "char_xp", number: 18, section: "characters", category: "Points & Levels",
    requirementType: "Backend", priority: "High", kind: "Clarification",
    currentUnderstanding: "Rewards come from mastering skills, and there are reading levels. The documents do not spell out a points system.",
    missingInformation: "Whether there are points, how they are earned, and whether a game level is different from a reading level.",
    whyWeNeedThis: "The points rules drive the behind-the-scenes math, the balance and the rewards.",
    impact: "Without these rules, we cannot build the progress math or the reports.",
    question: "If children earn points: How are points earned? Is every activity worth the same? Is there a daily limit? Can points be lost? And is a child's game level different from their reading level?",
    developerNote: "Backend, Game Design, Database.",
    reference: "Duolingo points and leagues. Khan Academy mastery points.",
    input: "paragraph",
  },
  {
    id: "char_rewards", number: 19, section: "characters", category: "Rewards",
    requirementType: "Gameplay", priority: "Medium", kind: "Confirmation + Clarification",
    currentUnderstanding: "Rewards come from mastering skills. The documents mention collectibles and costumes, but not badges.",
    confirmationStatement: "Children earn rewards for mastering skills, including things to collect and costumes.",
    missingInformation: "The full set of rewards, and whether there are badges or achievements.",
    whyWeNeedThis: "Rewards keep children motivated, and they connect to the backpack and shop.",
    impact: "Weak rewards hurt how often children come back.",
    question: "Beyond costumes and collectibles, what should make a child feel proud and want to come back? Tick all that apply.",
    developerNote: "Game Design, Backend, Art.",
    reference: "Duolingo achievements. Monopoly GO reward moments.",
    input: "multi_select",
    options: [
      { value: "stars", label: "Stars or points" },
      { value: "coins", label: "Coins or gems to spend" },
      { value: "outfits", label: "Outfits and character items" },
      { value: "pets", label: "Pets or buddies" },
      { value: "collectibles", label: "Things to collect (Heart Shards, treasures)" },
      { value: "story", label: "New story to unlock" },
      { value: "badges", label: "Badges or achievements" },
    ],
  },

  // Items, Quests & Coins
  {
    id: "sys_economy", number: 20, section: "systems", category: "Coins & a Reward Shop",
    requirementType: "Backend", priority: "Medium", kind: "New requirement",
    currentUnderstanding: "The documents do not mention coins or a shop.",
    missingInformation: "Whether there are coins, how they are earned or bought, and whether there is a reward shop.",
    whyWeNeedThis: "Coins add work behind the scenes and connect to how people pay.",
    impact: "Adding this late is costly. If it is not wanted, we skip the extra work.",
    question: "Should children earn coins to spend in a reward shop? If yes, should coins be earned only through learning, or ever bought with real money?",
    developerNote: "Backend, Game Design, Business.",
    reference: "Hay Day coins that you earn, versus buy-with-money games.",
    input: "single_select",
    options: [
      { value: "earned", label: "Earned only through learning" },
      { value: "earned_buy", label: "Earned, with the option to buy later" },
      { value: "none", label: "No coins at all" },
      { value: "decide", label: "Let your team decide" },
    ],
  },
  {
    id: "sys_inventory", number: 21, section: "systems", category: "The Backpack (Items)",
    requirementType: "Backend", priority: "Medium", kind: "Confirmation + Clarification",
    currentUnderstanding: "A backpack, or item store, for holding things is part of the plan.",
    confirmationStatement: "The game has a place to hold items, like a backpack.",
    missingInformation: "What it holds (outfits, quest items, collectibles), and whether children wear or use these items.",
    whyWeNeedThis: "Knowing the item types shapes the backpack, the rewards and the saved data.",
    impact: "Without this, we cannot design the backpack or the saving.",
    question: "What should a child's backpack hold, like outfits, collectibles such as Heart Shards, or quest items? And can they wear or use these things?",
    developerNote: "Backend, Game Design, Frontend.",
    reference: "Minecraft's inventory. If it should feel like that, tell us what is different.",
    input: "paragraph",
  },
  {
    id: "sys_quests", number: 22, section: "systems", category: "Quests & Missions",
    requirementType: "Gameplay", priority: "High", kind: "Confirmation + Clarification",
    currentUnderstanding: "There are main story quests and side quests. Reading quests carry the lessons.",
    confirmationStatement: "The game uses main quests and side quests to deliver the learning.",
    missingInformation: "The kinds of quests, whether they branch, and roughly how many per region at launch.",
    whyWeNeedThis: "The quest setup drives the quest system and how much content we build.",
    impact: "Unknown quest counts make time estimates unreliable.",
    question: "What kinds of quests do you picture, like story missions, skill challenges or collecting things? And roughly how many should one region have?",
    developerNote: "Game Design, Backend, Content.",
    reference: "Genshin's variety of quests. Duolingo's skill units.",
    input: "paragraph",
  },
  {
    id: "sys_notifications", number: 23, section: "systems", category: "Reminders & Alerts",
    requirementType: "Backend", priority: "Medium", kind: "Confirmation + Clarification",
    currentUnderstanding: "Alerts to teachers or specialists are implied (for example, when a child needs help). Other reminders are not set.",
    confirmationStatement: "The game will alert teachers or specialists when a child needs attention.",
    missingInformation: "Which moments send a message, and by what channel (in-app, email, or phone) for each person.",
    whyWeNeedThis: "These rules drive the alerts and the messaging tools.",
    impact: "Without clear triggers, important moments (like a struggling child) can be missed.",
    question: "Which moments should send a nudge or alert, and to whom (child, parent, teacher, specialist), and how (in-app, email or text)?",
    developerNote: "Backend, Messaging, UX.",
    input: "paragraph",
  },

  // Reading & Smart Help
  {
    id: "learn_engine", number: 24, section: "learning", category: "How Reading Is Taught",
    requirementType: "AI", priority: "Critical", kind: "Confirmation + Clarification",
    currentUnderstanding: "The 'Literacy DNA' system is planned. It includes a starting check, placing each child at the right level, reading levels, help paths, and mastery checks. Skills include letter sounds, sounding out words, word parts, vocabulary, fluency, understanding, spelling and writing. Writing help now, math help later.",
    confirmationStatement: "Literacy DNA (the starting check, placement, levels, mastery and help paths) is the core teaching system, and the listed reading skills are all in scope.",
    missingInformation: "The full details: how the starting check works, how a child is placed, exactly what counts as 'mastered', and which skills are in the first version.",
    whyWeNeedThis: "This is the heart of the product. Nothing that adjusts to the child can be built well without it.",
    impact: "This is the single biggest blocker. The core cannot be built correctly without these details.",
    question: "Could you share, or build with us, the full details of how reading is taught? How the starting check works, how a child is placed, exactly what counts as 'mastered', and which reading skills must be in the first version.",
    developerNote: "Reading, AI, Backend, Testing.",
    reference: "Well-known step-by-step reading programs.",
    input: "paragraph", required: true,
  },
  {
    id: "learn_ai", number: 25, section: "learning", category: "How the Game Adjusts",
    requirementType: "AI", priority: "High", kind: "Confirmation + Clarification",
    currentUnderstanding: "The documents mention making things easier or harder, personal lessons, suggestions, smart placement, and progress predictions. The meeting made clear this should follow set rules, not decide on its own.",
    confirmationStatement: "The smart part follows clear rules that your team sets. It does not make learning decisions on its own.",
    missingInformation: "The actual rules, and whether you want AI to help draft lesson content behind the scenes.",
    whyWeNeedThis: "The rules run the system. Using AI to draft content is a separate choice with its own cost and safety care.",
    impact: "Without the rules we cannot build the 'adjusting' part. Unmanaged AI raises child-safety concerns.",
    question: "Please describe the rules the game should follow to make something easier or harder. And would you like AI to help draft lesson content behind the scenes, always checked by a person first?",
    developerNote: "AI, Backend, Reading.",
    reference: "Duolingo's practice that adjusts. Khan Academy's mastery approach.",
    input: "paragraph",
  },
  {
    id: "learn_chatbot", number: 26, section: "learning", category: "A Chat Helper",
    requirementType: "AI", priority: "Low", kind: "New requirement",
    currentUnderstanding: "No chat helper is mentioned. Help is expected to come from the Lexi Guides.",
    missingInformation: "Whether you want any chat helper, for children or for parents and teachers.",
    whyWeNeedThis: "A chat helper is a separate feature with safety and moderation needs, especially for children.",
    impact: "If it is not planned but later expected, it adds work. If never wanted, we skip it.",
    question: "Do you want any kind of chat helper, either for children in the game, or for parents and teachers in their view? Or should help stay scripted through the Lexi Guides?",
    developerNote: "AI, Backend, Safety.",
    reference: "Duolingo's 'explain my answer' helper, made for grown-ups.",
    input: "single_select",
    options: [
      { value: "children", label: "Yes, a helper for children in the game" },
      { value: "adults", label: "Yes, for parents and teachers in their view" },
      { value: "scripted", label: "No, keep help scripted through the guides" },
      { value: "unsure", label: "Not sure" },
    ],
  },
  {
    id: "learn_reporting", number: 27, section: "learning", category: "Progress Reports",
    requirementType: "Backend", priority: "Medium", kind: "Confirmation + Clarification",
    currentUnderstanding: "Reports for parents, teachers and specialists, plus student progress, are part of the plan.",
    confirmationStatement: "The product gives progress reports for parents, teachers and specialists.",
    missingInformation: "The exact things each person needs to see, and any need to download reports.",
    whyWeNeedThis: "Knowing the exact numbers shapes the reports and dashboards.",
    impact: "Vague numbers lead to reports that do not answer real questions.",
    question: "For each grown-up (parent, teacher, specialist), what are the two or three most important things they should see at a glance about a child's reading?",
    developerNote: "Backend, Data, Frontend, Reading.",
    input: "paragraph",
  },
  {
    id: "learn_qa", number: 28, section: "learning", category: "Knowing It Really Works",
    requirementType: "QA", priority: "High", kind: "Clarification",
    currentUnderstanding: "Mastering a skill opens the next one, but the exact meaning of 'mastered' and how we prove it works are not set.",
    missingInformation: "The exact meaning of 'mastered', and how we check that real reading improves.",
    whyWeNeedThis: "Testing a learning product must prove children actually learn, not just that buttons work.",
    impact: "Without a clear meaning, we cannot prove the game truly teaches.",
    question: "How will we know a child has truly 'mastered' a skill? And how would you like to prove the game improves reading, for example by testing with real children first?",
    developerNote: "Testing, Reading, Product.",
    input: "paragraph",
  },

  // Playing With Others
  {
    id: "social_mode", number: 29, section: "social", category: "Playing With Others",
    requirementType: "Gameplay", priority: "Medium", kind: "Clarification",
    currentUnderstanding: "Teams (guilds) are mentioned. Otherwise it reads as a game you play on your own.",
    missingInformation: "Whether any playing-with-others is wanted, and for which stage.",
    whyWeNeedThis: "Playing with others adds work, live features, and extra care to keep children safe.",
    impact: "Guessing wrong either makes the first version too big or leaves out something you wanted.",
    question: "Is Lexi World mostly a solo journey, or do you want children to connect, like seeing friends' progress, joining teams, or playing together?",
    developerNote: "Backend, Game Design, Safety.",
    reference: "Duolingo's light, safe friends and leagues.",
    input: "single_select",
    options: [
      { value: "solo", label: "Solo. Just the child and the story" },
      { value: "friends", label: "Solo, but they can see friends' or classmates' progress" },
      { value: "teamup", label: "They can play or team up with others" },
      { value: "unsure", label: "Not sure" },
    ],
  },
  {
    id: "social_leaderboard", number: 30, section: "social", category: "Friendly Competition",
    requirementType: "Gameplay", priority: "Low", kind: "Clarification",
    currentUnderstanding: "Not mentioned. Competition helps some children but can discourage children who find reading hard.",
    missingInformation: "Whether you want any competition, like leaderboards.",
    whyWeNeedThis: "Competition changes how children feel, and can help or hurt the children we serve.",
    impact: "The wrong choice can discourage the very children the game is for.",
    question: "Would friendly competition, like leaderboards, motivate your children? Or would you rather avoid it so children who struggle never feel behind?",
    developerNote: "Game Design, Backend.",
    reference: "Duolingo Leagues, which you can opt into.",
    input: "single_select",
    options: [
      { value: "include", label: "Yes, add friendly competition" },
      { value: "avoid", label: "No, avoid it" },
      { value: "advise", label: "Let your team advise" },
    ],
    visibleWhen: { questionId: "social_mode", anyOf: ["friends", "teamup"] },
  },
  {
    id: "social_guild", number: 31, section: "social", category: "Teams (Guilds)",
    requirementType: "Gameplay", priority: "Low", kind: "Confirmation + Clarification",
    currentUnderstanding: "Teams (guilds) are listed as an idea.",
    confirmationStatement: "Teams (guilds) are part of the world you pictured.",
    missingInformation: "What a team actually does, and whether it is for launch or later.",
    whyWeNeedThis: "Teams mean live features and extra safety care for children.",
    impact: "Building teams early is costly. Ignoring a feature you want is a letdown.",
    question: "When you picture 'teams', what do children actually do in them, like belonging to a group or working toward shared goals? And is this for launch or a later dream?",
    developerNote: "Backend, Game Design, Safety.",
    reference: "Clash Royale clans, made simple and safe.",
    input: "paragraph",
    visibleWhen: { questionId: "social_mode", anyOf: ["teamup", "friends"] },
  },

  // Devices & Setup
  {
    id: "plat_platforms", number: 32, section: "platform", category: "Which Devices",
    requirementType: "Technical", priority: "High", kind: "Confirmation + Clarification",
    currentUnderstanding: "The target devices are iPad, Android, Windows, Mac, Chromebook and web. A colourful, simple art style is planned partly to run well on school devices.",
    confirmationStatement: "The game will run on iPad, Android, Windows, Mac, Chromebook and the web.",
    missingInformation: "Which devices must be ready first.",
    whyWeNeedThis: "Which devices come first affects the work, the testing and the art choices. School laptops need lighter art.",
    impact: "Doing all devices at once means much more testing. Not knowing the order risks over-building.",
    question: "Which devices must be ready on day one? Tick your launch devices, and the rest can follow.",
    developerNote: "Frontend, DevOps, Testing.",
    input: "multi_select",
    options: [
      { value: "ipad", label: "iPad or tablet" },
      { value: "android", label: "Android" },
      { value: "windows", label: "Windows" },
      { value: "mac", label: "Mac" },
      { value: "chromebook", label: "Chromebook" },
      { value: "web", label: "Web browser" },
    ],
  },
  {
    id: "plat_engine", number: 33, section: "platform", category: "How It's Built & the Look",
    requirementType: "Technical", priority: "High", kind: "Confirmation + Clarification",
    currentUnderstanding: "The plan is to build it in Unity and to buy ready-made, mix-and-match art in a colourful, medium-detail style (a starter art budget of about $500 to $2,500).",
    confirmationStatement: "Build in Unity, using bought mix-and-match art in a colourful, medium-detail style.",
    missingInformation: "Your okay on Unity, and a few real examples of the look you love.",
    whyWeNeedThis: "The build choice lets us start buying art. Real examples stop the art from going the wrong way.",
    impact: "No okay means we cannot start the technical base or buy art.",
    question: "Are you happy to build in Unity and use bought art that we then make our own, in a colourful style? Pick one, and share a few games or shows whose look you love in the note.",
    developerNote: "Game Dev, Art, DevOps.",
    reference: "Please share examples, like a colourful look such as Genshin, or a softer storybook look.",
    input: "single_select",
    options: [
      { value: "proceed", label: "Yes, go ahead as described" },
      { value: "unity_art", label: "Yes to Unity, but let's talk about the look" },
      { value: "decide", label: "Let your team decide" },
      { value: "other", label: "We have a different idea" },
    ],
  },
  {
    id: "plat_integrations", number: 34, section: "platform", category: "Connecting to Other Tools",
    requirementType: "Technical", priority: "Medium", kind: "New requirement",
    currentUnderstanding: "No existing tools or connections are mentioned.",
    missingInformation: "Whether we must connect to any website, app, sign-in, content tool, or school system you already use.",
    whyWeNeedThis: "Connections shape the setup and the work from the very start.",
    impact: "Connections found late cause rework.",
    question: "Do you already have anything built, like a website, app, sign-in, or content tools, that Lexi World must connect to? Or are we starting fresh?",
    developerNote: "Backend, DevOps.",
    input: "single_select",
    options: [
      { value: "fresh", label: "Starting fresh" },
      { value: "integrate", label: "Yes, we must connect to something (add details)" },
      { value: "unsure", label: "Not sure" },
    ],
  },
  {
    id: "plat_infra", number: 35, section: "platform", category: "Where It's Stored",
    requirementType: "Infrastructure", priority: "Low", kind: "New requirement",
    currentUnderstanding: "No storage preferences are set. This is usually our call.",
    missingInformation: "Any preference for where the app and children's data are stored, or any rule about the country.",
    whyWeNeedThis: "Rules, like a required country or an existing account, affect the setup.",
    impact: "Unknown rules can clash with school contracts later.",
    question: "Do you have any preference or rule about where the app and children's data are stored, like a specific country or an account you already have? If not, we will pick the best option.",
    developerNote: "DevOps, Safety.",
    input: "single_select",
    options: [
      { value: "decide", label: "No preference. You decide" },
      { value: "preference", label: "We have a preference or rule (add details)" },
    ],
  },
  {
    id: "plat_offline", number: 36, section: "platform", category: "Playing Without Internet",
    requirementType: "Technical", priority: "Medium", kind: "New requirement",
    currentUnderstanding: "Not covered. Cloud saving suggests it expects to be online.",
    missingInformation: "Whether children must be able to play with no internet.",
    whyWeNeedThis: "Offline play changes the data and the setup quite a lot.",
    impact: "Adding offline later is costly. Knowing now shapes the design.",
    question: "Do children need to keep playing when there is no internet, or is an internet connection always fine?",
    developerNote: "Frontend, Backend.",
    input: "single_select",
    options: [
      { value: "offline", label: "It should work offline too" },
      { value: "online", label: "Online is fine" },
      { value: "decide", label: "Let your team decide" },
    ],
  },
  {
    id: "plat_localization", number: 37, section: "platform", category: "Other Languages",
    requirementType: "Technical", priority: "Low", kind: "New requirement",
    currentUnderstanding: "Not mentioned. Likely English first.",
    missingInformation: "Whether other languages are planned, now or later.",
    whyWeNeedThis: "Planning for other languages early is far cheaper than adding it later.",
    impact: "No language plan can force costly rework if you expand.",
    question: "Is Lexi World English only for now, or should we build it so other languages can be added later?",
    developerNote: "Frontend, Content.",
    input: "single_select",
    options: [
      { value: "english", label: "English only for now" },
      { value: "future", label: "Build so languages can be added later" },
      { value: "unsure", label: "Not sure" },
    ],
  },
  {
    id: "plat_audio", number: 38, section: "platform", category: "Sound & Voice",
    requirementType: "Technical", priority: "Medium", kind: "Confirmation + Clarification",
    currentUnderstanding: "Music, voice, sound effects and background sounds are planned (a sound person joins later).",
    confirmationStatement: "The game will have music, voice and sound effects.",
    missingInformation: "How much is voiced, whether the voice is recorded by people or made by computer, and whether the game should listen to a child reading aloud.",
    whyWeNeedThis: "Voice is a big cost. Listening to a child read is a large feature.",
    impact: "Unclear sound scope can swing the budget a lot.",
    question: "Should every word be read aloud (and in what kind of voice)? And would you like the game to listen to a child reading aloud to check their reading?",
    developerNote: "Audio, AI (speech), Backend.",
    reference: "Duolingo's spoken prompts. Reading-check tools.",
    input: "paragraph",
  },
  {
    id: "plat_accounts", number: 39, section: "platform", category: "Sign-in & Accounts",
    requirementType: "Backend", priority: "Critical", kind: "Confirmation + Clarification",
    currentUnderstanding: "Student accounts and a sign-in are planned. Parent, teacher and specialist accounts are implied by their views.",
    confirmationStatement: "The product has accounts and sign-in for children and grown-ups, with the right access for each role.",
    missingInformation: "How parents give permission, whether schools need one-click sign-in and class lists, and whether siblings can share one account.",
    whyWeNeedThis: "Sign-in and class setup are a base part, needed early, especially for schools.",
    impact: "Getting this wrong blocks both home and school setup, and safety rules.",
    question: "For schools, will you need one-click sign-in and a way to load class lists (for example Clever or ClassLink)? And at home, can several brothers and sisters share one account?",
    developerNote: "Backend, Safety, Frontend.",
    reference: "Clever and ClassLink for school class lists.",
    input: "paragraph",
  },

  // Safety & Your Tools
  {
    id: "comp_security", number: 40, section: "compliance", category: "Keeping Children's Data Safe",
    requirementType: "Security", priority: "Critical", kind: "New requirement",
    currentUnderstanding: "Safety and data storage are noted, but no rules are set, and this handles children's data.",
    missingInformation: "Which child-privacy rules must be met (like COPPA and FERPA in the US), how permission works, how long data is kept, and who is responsible for the data.",
    whyWeNeedThis: "Child-data rules must be built in from day one, and schools often require this before they buy.",
    impact: "Gaps here can block school sales and cause legal trouble.",
    question: "Which privacy rules must we meet for your markets (for example COPPA and FERPA in the US)? And are there any data or permission rules your school partners will require?",
    developerNote: "Safety, Backend, Legal.",
    input: "paragraph", required: true,
  },
  {
    id: "comp_admin", number: 41, section: "compliance", category: "Your Behind-the-Scenes Tools",
    requirementType: "Backend", priority: "High", kind: "Confirmation + Clarification",
    currentUnderstanding: "Every lesson is approved by the founder before it goes into the game, which means there is a content pipeline. A behind-the-scenes tool is implied.",
    confirmationStatement: "There will be a content pipeline where lessons are made and approved before they go live.",
    missingInformation: "What the behind-the-scenes tool must do, and who uses it.",
    whyWeNeedThis: "This tool is a big part of the work and is often under-planned.",
    impact: "Under-planning the back office slows content and daily operations.",
    question: "Who on your team will make and approve lessons and content, and what should that behind-the-scenes tool let them do?",
    developerNote: "Backend, Frontend (admin), Content.",
    input: "paragraph",
  },
  {
    id: "comp_edgecases", number: 42, section: "compliance", category: "What-If Situations",
    requirementType: "QA", priority: "High", kind: "Clarification",
    currentUnderstanding: "The starting check can place children at different levels, but the documents do not cover the 'what if' situations that follow.",
    missingInformation: "What happens when two children are placed at different levels (same story or different?), when a child comes back after a long break, when brothers and sisters share one device, and when a child is stuck on a skill.",
    whyWeNeedThis: "These cases decide the core setup (one shared story, or a story that changes) and stop confusion later.",
    impact: "If left open, they lead to designs that clash and need rework.",
    question: "If Child A is placed at Level 3 and Child B at Level 1, should they see the same story or different starting points? And how should the game treat a child who comes back after a few weeks away, or brothers and sisters sharing one device?",
    developerNote: "Game Design, Backend, Reading.",
    input: "paragraph", required: true,
  },
];

export function questionsBySection(sectionId: string): Question[] {
  return QUESTIONS.filter((q) => q.section === sectionId);
}

export function getQuestion(id: string): Question | undefined {
  return QUESTIONS.find((q) => q.id === id);
}

// Rough seconds per question, used for the time-left estimate.
export const AVG_SECONDS_PER_QUESTION = 55;
